#!/bin/sh
./rewrite-slrepo-more-mirrors-riken
yum clean all
yum -y update
yum -y groupinstall 'Development Tools'
yum -y install kernel-devel
yum -y install gnome-tweak-tool gnome-shell-extension-no-hot-corner
yum -y install zsh mercurial screen redhat-lsb-core nmap-ncat telnet tcpdump wireshark-gnome
yum -y install lsof bind-utils strace ltrace man-pages wget vim sysstat
yum -y insatll emacs
yum -y install boost-devel libuuid-devel mod_wsgi
distribution=$(lsb_release -si)
if [ x$distribution = xScientific ]; then
    yum -y install yum-conf-epel
elif [ x$distribution = xCentOS ]; then
    yum -y install epel-release
fi
yum-config-manager --disable epel
yum -y --enablerepo=epel install wxPython
yum -y --enablerepo=epel install nkf

# reboot
